# Generated by Django 5.1.5 on 2025-03-23 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_students_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='department',
            new_name='Qualification',
        ),
    ]
