# Generated by Django 5.1.5 on 2025-03-23 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_rename_department_faculty_qualification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='description',
        ),
    ]
